version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mongo_network

  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_container
    ports:
      - "3000:3000"
    networks:
      - mongo_network
    environment:
      MONGO_URI: mongodb://mongo_container:27017/ozmap
    env_file:
      - .env
    depends_on:
      - mongo

networks:
  mongo_network:
    driver: bridge