version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge